/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutCard: typeof import('./src/components/settings/AboutCard.vue')['default']
    AccountCard: typeof import('./src/components/settings/AccountCard.vue')['default']
    AppearanceCard: typeof import('./src/components/settings/AppearanceCard.vue')['default']
    AppModal: typeof import('./src/components/AppModal.vue')['default']
    BatchActionBar: typeof import('./src/components/BatchActionBar.vue')['default']
    BehaviorCard: typeof import('./src/components/settings/BehaviorCard.vue')['default']
    CreateGroupButton: typeof import('./src/components/CreateGroupButton.vue')['default']
    GroupActionsMenu: typeof import('./src/components/GroupActionsMenu.vue')['default']
    GroupCoverCard: typeof import('./src/components/GroupCoverCard.vue')['default']
    GroupFormModal: typeof import('./src/components/GroupFormModal.vue')['default']
    MemeActionsMenu: typeof import('./src/components/MemeActionsMenu.vue')['default']
    MemeCard: typeof import('./src/components/MemeCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerCard: typeof import('./src/components/settings/ServerCard.vue')['default']
    ShortcutCard: typeof import('./src/components/settings/ShortcutCard.vue')['default']
    TagEditorModal: typeof import('./src/components/TagEditorModal.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    UApp: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UDashboardGroup: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardNavbar: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue')['default']
    UDashboardPanel: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
    UDashboardSidebar: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UDashboardSidebarCollapse: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue')['default']
    UDashboardSidebarToggle: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarToggle.vue')['default']
    UDropdownMenu: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UForm: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./../node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UNavigationMenu: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPageCard: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue')['default']
    UPageGrid: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/PageGrid.vue')['default']
    UploadMemeButton: typeof import('./src/components/UploadMemeButton.vue')['default']
    UploadMemeModal: typeof import('./src/components/UploadMemeModal.vue')['default']
    UProgress: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    USelectMenu: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USwitch: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
  }
}

// For TSX support
declare global {
  const AboutCard: typeof import('./src/components/settings/AboutCard.vue')['default']
  const AccountCard: typeof import('./src/components/settings/AccountCard.vue')['default']
  const AppearanceCard: typeof import('./src/components/settings/AppearanceCard.vue')['default']
  const AppModal: typeof import('./src/components/AppModal.vue')['default']
  const BatchActionBar: typeof import('./src/components/BatchActionBar.vue')['default']
  const BehaviorCard: typeof import('./src/components/settings/BehaviorCard.vue')['default']
  const CreateGroupButton: typeof import('./src/components/CreateGroupButton.vue')['default']
  const GroupActionsMenu: typeof import('./src/components/GroupActionsMenu.vue')['default']
  const GroupCoverCard: typeof import('./src/components/GroupCoverCard.vue')['default']
  const GroupFormModal: typeof import('./src/components/GroupFormModal.vue')['default']
  const MemeActionsMenu: typeof import('./src/components/MemeActionsMenu.vue')['default']
  const MemeCard: typeof import('./src/components/MemeCard.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const ServerCard: typeof import('./src/components/settings/ServerCard.vue')['default']
  const ShortcutCard: typeof import('./src/components/settings/ShortcutCard.vue')['default']
  const TagEditorModal: typeof import('./src/components/TagEditorModal.vue')['default']
  const TitleBar: typeof import('./src/components/TitleBar.vue')['default']
  const UApp: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  const UBadge: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
  const UButton: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
  const UCard: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
  const UDashboardGroup: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
  const UDashboardNavbar: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue')['default']
  const UDashboardPanel: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
  const UDashboardSidebar: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
  const UDashboardSidebarCollapse: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue')['default']
  const UDashboardSidebarToggle: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarToggle.vue')['default']
  const UDropdownMenu: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
  const UForm: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
  const UFormField: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
  const UIcon: typeof import('./../node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
  const UInput: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
  const UModal: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
  const UNavigationMenu: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
  const UPageCard: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue')['default']
  const UPageGrid: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/PageGrid.vue')['default']
  const UploadMemeButton: typeof import('./src/components/UploadMemeButton.vue')['default']
  const UploadMemeModal: typeof import('./src/components/UploadMemeModal.vue')['default']
  const UProgress: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
  const USelectMenu: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
  const USwitch: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
}